"""Add support for TOTP 2fa

Revision ID: 7050ccf1d55d
Revises: 5211735c3bab
Create Date: 2025-01-22 20:15:56.446189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7050ccf1d55d'
down_revision: Union[str, None] = '5211735c3bab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'usernames', ['id'])
    op.add_column('users', sa.Column('totp', sa.Boolean(), server_default='0', nullable=False))
    op.add_column('users', sa.Column('totpSecret', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'totpSecret')
    op.drop_column('users', 'totp')
    op.drop_constraint(None, 'usernames', type_='unique')
    # ### end Alembic commands ###
