"""changed active to active_status

Revision ID: 8dc934cbac64
Revises: 7050ccf1d55d
Create Date: 2025-01-22 20:29:22.663756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8dc934cbac64'
down_revision: Union[str, None] = '7050ccf1d55d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('active_status', sa.Boolean(), server_default='0', nullable=False))
    op.drop_column('users', 'active')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('active', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_column('users', 'active_status')
    # ### end Alembic commands ###
