"""table data

Revision ID: fb01cb4bf401
Revises: 8dc934cbac64
Create Date: 2025-01-23 16:36:17.046921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fb01cb4bf401'
down_revision: Union[str, None] = '8dc934cbac64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('satellites',
    sa.Column('object_name', sa.String(), nullable=False),
    sa.Column('object_id', sa.String(), nullable=False),
    sa.Column('epoch', sa.String(), nullable=False),
    sa.Column('mean_motion', sa.Double(), server_default='0', nullable=False),
    sa.Column('eccentricity', sa.Double(), server_default='0', nullable=True),
    sa.Column('inclination', sa.Double(), server_default='0', nullable=False),
    sa.Column('ra_of_asc_node', sa.Double(), server_default='0', nullable=False),
    sa.Column('arg_of_pericenter', sa.Double(), server_default='0', nullable=True),
    sa.Column('mean_anomaly', sa.Double(), server_default='0', nullable=False),
    sa.Column('ephemeris_type', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('classification_type', sa.String(), nullable=False),
    sa.Column('norad_cat_id', sa.Integer(), server_default='0', nullable=False),
    sa.Column('element_set_no', sa.Integer(), server_default='0', nullable=False),
    sa.Column('rev_at_epoch', sa.Integer(), server_default='0', nullable=False),
    sa.Column('bstar', sa.Double(), server_default='0', nullable=False),
    sa.Column('mean_motion_dot', sa.Double(), server_default='0', nullable=False),
    sa.Column('mean_motion_ddot', sa.Double(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('object_name'),
    sa.UniqueConstraint('object_id'),
    sa.UniqueConstraint('object_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usernames',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('userid', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['userid'], ['users.id'], name='usernames_userid_fkey'),
    sa.PrimaryKeyConstraint('id', name='usernames_pkey'),
    sa.UniqueConstraint('id', name='usernames_id_key'),
    sa.UniqueConstraint('username', name='usernames_username_key')
    )
    op.create_table('users',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('lastActivity', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('IsAdmin', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('isBanned', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('totp', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('totpSecret', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('active_status', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    sa.UniqueConstraint('email', name='users_email_key'),
    sa.UniqueConstraint('id', name='users_id_key')
    )
    op.drop_table('satellites')
    # ### end Alembic commands ###
